"""Add enrolled_students to AcademicRecord

Revision ID: af646b3a3955
Revises: 208bb5bb7c65
Create Date: 2026-04-30 22:50:04.174035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af646b3a3955'
down_revision: Union[str, None] = '208bb5bb7c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_records', sa.Column('enrolled_students', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_records', 'enrolled_students')
    # ### end Alembic commands ###
