"""Add coordinates to institutions

Revision ID: b3d9e0462eaa
Revises: af646b3a3955
Create Date: 2026-05-02 11:23:07.715237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d9e0462eaa'
down_revision: Union[str, None] = 'af646b3a3955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('institutions', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'longitude')
    op.drop_column('institutions', 'latitude')
    # ### end Alembic commands ###
