"""initial schema

Revision ID: c8215b30f501
Revises: 
Create Date: 2026-04-30 01:32:17.286095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8215b30f501'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('institution_type', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('academic_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('attendance_rate', sa.Float(), nullable=True),
    sa.Column('repetition_rate', sa.Float(), nullable=True),
    sa.Column('dropout_rate', sa.Float(), nullable=True),
    sa.CheckConstraint('attendance_rate BETWEEN 0 AND 100', name='ck_academic_attendance'),
    sa.CheckConstraint('dropout_rate    BETWEEN 0 AND 100', name='ck_academic_dropout'),
    sa.CheckConstraint('repetition_rate BETWEEN 0 AND 100', name='ck_academic_repetition'),
    sa.CheckConstraint('success_rate    BETWEEN 0 AND 100', name='ck_academic_success'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_records_institution_id'), 'academic_records', ['institution_id'], unique=False)
    op.create_index(op.f('ix_academic_records_semester'), 'academic_records', ['semester'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('kpi_domain', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message_fr', sa.Text(), nullable=True),
    sa.Column('message_ar', sa.Text(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_institution_id'), 'alerts', ['institution_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_institution_id'), 'chat_sessions', ['institution_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_institution_id'), 'documents', ['institution_id'], unique=False)
    op.create_table('employment_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('employability_rate', sa.Float(), nullable=True),
    sa.Column('insertion_delay_days', sa.Integer(), nullable=True),
    sa.Column('national_conventions', sa.Integer(), nullable=True),
    sa.Column('international_conventions', sa.Integer(), nullable=True),
    sa.CheckConstraint('employability_rate BETWEEN 0 AND 100', name='ck_employment_employability'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employment_records_institution_id'), 'employment_records', ['institution_id'], unique=False)
    op.create_index(op.f('ix_employment_records_year'), 'employment_records', ['year'], unique=False)
    op.create_table('esg_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('energy_kwh', sa.Float(), nullable=True),
    sa.Column('carbon_kg', sa.Float(), nullable=True),
    sa.Column('recycling_rate', sa.Float(), nullable=True),
    sa.Column('mobility_type', sa.String(), nullable=True),
    sa.CheckConstraint('recycling_rate BETWEEN 0 AND 100', name='ck_esg_recycling'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_records_institution_id'), 'esg_records', ['institution_id'], unique=False)
    op.create_index(op.f('ix_esg_records_period'), 'esg_records', ['period'], unique=False)
    op.create_table('finance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('budget_allocated', sa.Float(), nullable=True),
    sa.Column('budget_consumed', sa.Float(), nullable=True),
    sa.Column('cost_per_student', sa.Float(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_records_institution_id'), 'finance_records', ['institution_id'], unique=False)
    op.create_index(op.f('ix_finance_records_period'), 'finance_records', ['period'], unique=False)
    op.create_table('hr_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('teaching_staff_count', sa.Integer(), nullable=True),
    sa.Column('admin_staff_count', sa.Integer(), nullable=True),
    sa.Column('absenteeism_rate', sa.Float(), nullable=True),
    sa.Column('training_hours', sa.Integer(), nullable=True),
    sa.CheckConstraint('absenteeism_rate BETWEEN 0 AND 100', name='ck_hr_absenteeism'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_records_institution_id'), 'hr_records', ['institution_id'], unique=False)
    op.create_index(op.f('ix_hr_records_period'), 'hr_records', ['period'], unique=False)
    op.create_table('infrastructure_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('room_occupancy_rate', sa.Float(), nullable=True),
    sa.Column('equipment_status', sa.String(), nullable=True),
    sa.Column('ongoing_works', sa.Integer(), nullable=True),
    sa.CheckConstraint('room_occupancy_rate BETWEEN 0 AND 100', name='ck_infra_occupancy'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_records_institution_id'), 'infrastructure_records', ['institution_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_records_period'), 'infrastructure_records', ['period'], unique=False)
    op.create_table('partnership_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('active_agreements', sa.Integer(), nullable=True),
    sa.Column('incoming_mobility', sa.Integer(), nullable=True),
    sa.Column('outgoing_mobility', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partnership_records_institution_id'), 'partnership_records', ['institution_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_institution_id'), 'reports', ['institution_id'], unique=False)
    op.create_table('research_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('publications', sa.Integer(), nullable=True),
    sa.Column('active_projects', sa.Integer(), nullable=True),
    sa.Column('funding_secured', sa.Float(), nullable=True),
    sa.Column('patents', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_records_institution_id'), 'research_records', ['institution_id'], unique=False)
    op.create_index(op.f('ix_research_records_year'), 'research_records', ['year'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_research_records_year'), table_name='research_records')
    op.drop_index(op.f('ix_research_records_institution_id'), table_name='research_records')
    op.drop_table('research_records')
    op.drop_index(op.f('ix_reports_institution_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_partnership_records_institution_id'), table_name='partnership_records')
    op.drop_table('partnership_records')
    op.drop_index(op.f('ix_infrastructure_records_period'), table_name='infrastructure_records')
    op.drop_index(op.f('ix_infrastructure_records_institution_id'), table_name='infrastructure_records')
    op.drop_table('infrastructure_records')
    op.drop_index(op.f('ix_hr_records_period'), table_name='hr_records')
    op.drop_index(op.f('ix_hr_records_institution_id'), table_name='hr_records')
    op.drop_table('hr_records')
    op.drop_index(op.f('ix_finance_records_period'), table_name='finance_records')
    op.drop_index(op.f('ix_finance_records_institution_id'), table_name='finance_records')
    op.drop_table('finance_records')
    op.drop_index(op.f('ix_esg_records_period'), table_name='esg_records')
    op.drop_index(op.f('ix_esg_records_institution_id'), table_name='esg_records')
    op.drop_table('esg_records')
    op.drop_index(op.f('ix_employment_records_year'), table_name='employment_records')
    op.drop_index(op.f('ix_employment_records_institution_id'), table_name='employment_records')
    op.drop_table('employment_records')
    op.drop_index(op.f('ix_documents_institution_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chat_sessions_institution_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_alerts_institution_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_academic_records_semester'), table_name='academic_records')
    op.drop_index(op.f('ix_academic_records_institution_id'), table_name='academic_records')
    op.drop_table('academic_records')
    op.drop_table('institutions')
    # ### end Alembic commands ###
